server:
  port: 9002

spring:
  application:
    name: cloud-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: 172.19.106.120:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'