server:
  port: 5001

spring:
  application:
    name: seata-order-service
  cloud:
    nacos:
      discovery:
        server-addr: 172.19.106.120:8848
    alibaba:
      seata:
        tx-service-group: define_test_group
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.19.106.120:3306/seata-order?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    io:
      seata: info

feign:
  hystrix:
    enabled: true

mybatis:
  mapperLocations: classpath*:mapper/*.xml
